service: instance-reboot
provider:
  name: aws
  runtime: python3.6
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cloudformation:ListStackResources"
        - "autoscaling:DescribeAutoScalingGroups"
        - "ec2:RebootInstances"
      Resource: "*"
functions:
  reboot:
    handler: handler.reboot
